#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Update-helloworld

on:
  workflow_dispatch:
#   schedule:
#     - cron: 05 20 * * *

jobs:

  prepare:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Load latest helloworld
      run: |
        git clone https://github.com/fw876/helloworld.git --depth=1 ./tmp/helloworld
        rm -rf ./package/lean/luci-app-ssr-plus && cp -rf ./tmp/helloworld/luci-app-ssr-plus ./package/lean/
        rm -rf ./package/lean/naiveproxy && cp -rf ./tmp/helloworld/naiveproxy ./package/lean/
        rm -rf ./package/lean/shadowsocks-rust && cp -rf ./tmp/helloworld/shadowsocks-rust ./package/lean/
        rm -rf ./package/lean/shadowsocksr-libev && cp -rf ./tmp/helloworld/shadowsocksr-libev ./package/lean/
        rm -rf ./package/lean/simple-obfs && cp -rf ./tmp/helloworld/simple-obfs ./package/lean/
        rm -rf ./package/lean/tcping && cp -rf ./tmp/helloworld/tcping ./package/lean/
        rm -rf ./package/lean/trojan && cp -rf ./tmp/helloworld/trojan ./package/lean/
        rm -rf ./package/lean/v2ray-core && cp -rf ./tmp/helloworld/v2ray-core ./package/lean/
        rm -rf ./package/lean/v2ray-plugin && cp -rf ./tmp/helloworld/v2ray-plugin ./package/lean/
        rm -rf ./package/lean/xray-core && cp -rf ./tmp/helloworld/xray-core ./package/lean/
        rm -rf ./package/lean/xray-plugin && cp -rf ./tmp/helloworld/xray-plugin ./package/lean/

    - name: Apply commit changes
      run: |
        git add ./package/lean/
        echo -e "[bot] luci-app-ssr-plus: update\n\nlatest commit: $(cat ./tmp/helloworld/.git/refs/heads/master)" > ./tmp/message
        git commit --file="./tmp/message" || exit 0

    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: master
      run: git push origin $DOWNSTREAM_BRANCH
